name: Lint & Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          # E203 and W503 break proper PEP 8. This run is just to issue warnings. The file limit is standard black.
          # See https://github.com/psf/black/blob/master/docs/compatible_configs.md#flake8
          flake8 . --count --ignore=E203,W503 --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      - name: Tests
        run: |
          python pytest.py
